### ISSUE TITLE
Set Up SAP Build Apps on SAP BTP Trial Account

### ISSUE THREAD

**Issue by Karunaharan** [sap-tutorials/sap-build-apps#12]
Tutorials: https://developers.sap.com/tutorials/build-apps-trial.html
--------------------------

While I try to follow the steps mentioned in Step 4, I don't see the role collections BuildApps_Administration and BuildApps_Developer in the SAP BTP trial account. I can see all 4 roles that are mentioned in the Security -> Roles section. While I can create a custom role collection, how do we fix this for other users? Please let me know.

Regards,
Karuna

**Comment by thecodester** [comment]
Thanks so much for bringing this to our attention ... my understanding is this has been fixed, and when I run the booster all is created for me OK.
