### ISSUE TITLE
Test CAP Service and its Destination

### ISSUE THREAD

**Issue by SK-2014** [sap-tutorials/sap-build-apps#15]
Tutorials: https://developers.sap.com/tutorials/build-apps-cap-expose.html
--------------------------
Hello Experts,

in step 2, why is the property set to Appgyver.Enabled = true
ideally it should be sap build setting property now isnt it?

Regards,
Saritha

**Comment by thecodester** [comment]
I do not know why they have not updated this by now, at least allowing either one.
