### ISSUE TITLE
Check Status of Process from SAP Build App

### ISSUE THREAD

**Issue by thhaddon** [sap-tutorials/sap-build-apps#16]
Tutorials: https://developers.sap.com/tutorials/build-apps-workflow-check-status.html
--------------------------

Write here how you think we can improve the tutorial ...

The answer to question at the end of section 6 "[Create data resource for status API](https://developers.sap.com/tutorials/build-apps-workflow-check-status.html#8c029eb1-766a-45a9-b7f5-25389100ff24)" should be "Retrieve action, GET method"

**Comment by thecodester** [comment]
This was fixed (a while ago) but thanks for pointing out.
