### ISSUE TITLE
Prepare a Product Page  - Formula Option not available in new UI anymore

### ISSUE THREAD

**Issue by Matthias-Adams** [sap-tutorials/sap-build-apps#647]
Tutorials: https://developers.sap.com/tutorials/build-apps-socialmedia-4-details-page.html
--------------------------

As part of the mission "Prepare a Product Page" -> Section 2 "Add variables to the page"
-> Step 5 Under Data Variables, add a data variable based on the Products entity

This step is not reproducible anymore.
In the new UI, if "Single data record" there is no further configuration option showed.
![image](https://github.com/user-attachments/assets/321a5255-928d-4c71-a5d9-63f71340aeac)

In contrast the tutorial wants to set a formula:
![image](https://github.com/user-attachments/assets/6bd75c17-aa10-429f-b57d-1964e1953e72)

This breaks the binding later. So don't see the ProductName on the detail page and the aggregated rating is not shown correclty.

FYI: @thecodester

**Comment by thecodester** [comment]
My understanding is there is a bug hat is to be fixed this week. I will monitor and update this issue when it is fixed ... @Matthias-Adams and if you notice it fixed let me know.

**Comment by thecodester** [comment]
The bug is resolved, and also we rewrote the entire mission of 5 tutorials.

I will close the issue. But if you need anything else, feel free to comment here or even reopen.

**Comment by Matthias-Adams** [comment]
Thanks!
