### ISSUE TITLE
Create SAP Build App to Trigger Workflow

### ISSUE THREAD

**Issue by horsemanjackyliu** [sap-tutorials/sap-build-apps#648]
Tutorials: https://developers.sap.com/tutorials/build-apps-workflow-trigger.html
--------------------------

Write here how you think we can improve the tutorial ...

If I follow the turorial , the issue is like the following video .

https://github.com/user-attachments/assets/607b9794-6045-4036-880c-b834616153a5

We have create app variable or page variable and bind them to input field .

**Comment by thecodester** [comment]
It seems o me hat there is an event on change of the data variable where you clear out the data variable. Do you have logic that clears the data variable?

**Comment by thecodester** [comment]
I will close this issue as I haven't heard back but if you have more issues please reopen
