### ISSUE TITLE
Create SAP Build App to Trigger Workflow

### ISSUE THREAD

**Issue by driesC-flexso** [sap-tutorials/sap-build-apps#650]
Tutorials: https://developers.sap.com/tutorials/build-apps-workflow-trigger.html
--------------------------

If the mission [Experience SAP Build By Creating an End-to-End Sales Scenario](https://developers.sap.com/mission.build-workshop-sales-order.html) is followed up until this tutorial, the 'Get Approval' button won't work, because there is no destination configured in the SAP BTP Cockpit. 

There should be a step to configure this, or a reference to the first step of [7 - Trigger Process from Your App](https://developers.sap.com/tutorials/codejam-07-connect-app-process..html).

**Comment by thecodester** [comment]
Thanks for the comment. We have now added a prerequisite pointing directly to the section you mentioned. Thanks, @driesC-flexso :-)
